### Status check

GET http://localhost:3000 HTTP/1.1


### Get all Tasks

GET http://localhost:3000/tasks HTTP/1.1


### Create new task

POST http://localhost:3000/tasks HTTP/1.1
Content-Type: application/json

{
  "title": "Hello World!"
}


### Delete task with id

DELETE http://localhost:3000/tasks/delete/f631d0e9-acf1-48cb-9b73-58032ccb0c89 HTTP/1.1


### Update task with id

PUT http://localhost:3000/tasks/update/8f632aca-411e-48f3-8b3a-73d460f5862b HTTP/1.1
Content-Type: application/json

{
  "title": "This is a new title."
}


### Bad request

GET http://localhost:3000/users HTTP/1.1
